name: gorouterauth
description: "GoRouter Authentication."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  cupertino_icons: ^1.0.2
  go_router: ^13.0.1

  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3

  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  custom_lint: ^0.5.7
  riverpod_lint: ^2.3.7
  build_runner: ^2.4.7
  riverpod_generator: ^2.3.9

  go_router_builder: ^2.4.1

flutter:
  uses-material-design: true
